#!/usr/bin/python
#
#
# requirements: 
#     - python 2.5 or above, must be able to use threads
#     - nmap 5.0 or above  including ndiff
#     - unprivilegded user with sudo-rights for chgroup 
#
# todo: 
#   - modus:nagios/standalone
#   - profile: mailto= 
#
# commands-examples:
#
#
# define  command {
    # command_name    check_nmap
    # command_line    $USER1$/check_nmap -x $ARG1$
    # }

    

# define  service {
        # host_name               nmap_scan_host
        # service_description     nmap_scan
        # check_command           check_nmap![profile-name]
        # use                     generic-service
        # register                1

# }

# cronjob
# checks all 10 minutes for profil-name 
# */10 * * * * /etc/nagios/plugins/check_nmap -s profil-name


import time, socket, thread, sys, os, getopt, string

version = "0.4.36 - 2013-01-19"

#
# config_start
#

debug = "no"

data_dir = "/var/lib/check_nmap"
nmap_exec = "/usr/bin/nmap"
ndiff_exec = "/usr/bin/ndiff"
nmap_switches = "-PN -T5 -sV " # maybe tweak this for better performance 
nmap_ports = "-p U:1-,T:1-"
nagios_version = 3
nagios_group = "nagios" # for chmodding/chowning scan-files

# use this for later reasons
profiles = {
       # 'profile-name', 'profile-description'
       # profile-name should be single name with alphanumeric chars, no spaces
        'standard':'Basic scan of localhost',
           }



# after which time an unaltered nmap_asctual.scan - file 
# will create an alert (cron stopped, broken nmap etc)

# defaults 
scan_fresh_warning  = 1440
scan_fresh_critical = 2880

# this is needed for standalone-modus
default_email = "root@localhost"
mail_modus = "localhost" # might be: smarthost
# this is only neede for mail_modus = "smarthost"
smtp_server = ""
smtp_port = 25
smtp_user = ""
smtp_pass = ""
smtp_ssl = "no" # if yes -> port = 995

#
# config_end
#


def check_nmap_help():
    
    print """

check_nmap  - version: %s
Copyright 2009,2010,2011,2012,2013 mare-system / dogtown@mare-system.de    

This plugin tests for nmap-diffs on a given server-list

       it runs in three different modi:
        -i [profile-name] 
            create initial scan; interactively if no server.lst is
            found
            
        -s [profile-name] 
            create actual scan_result (should be run from an unprivilegded
            users crontab, eg every hour, depending on your network
            and level of paranoia)
            

        -x [profile-name]
            execute scan/ ndiff: check actual_scan_result against 
            initial_scan_result should be executed as nagios-check

Please note: the modes -i / -s might take a long time if using default-values
    due to the fact that the full portrange is used (-p U:1-,T:1-)
    

this is still in testing (late alpha/early beta) and should
be wisely tested before executed against a larger network

***) => still to be done

USAGE:
   check_nmap -x profile-name [ -w minutes -c minutes ]

OPTIONS 
    -h                 -> help
    

  modes:
    -i profile-name    -> create initial scan_result
    -s profile-name    -> create actual scan_result 
                         (should be run from crontab, eg every hour)
    -x profile-name    -> execute scan/ ndiff: check actual_scan_result 
                          against initial_scan_result 
                          should be executed as nagios-check

  Options: 
    -P                 -> skip nmap-ping-scan (should NOT be used when
                          scanning a list of networks, e.g. 192.168.100.0/24,
                          because othervise -PN is used for nmap, assuming you know
                          the servers are up and running, but pings might get blocked
                          default: -PN is OFF

    -p [ports]         -> give nmap-style portrange e.g. 
                          -p22; -p1-65535; -p U:53,111,137,T:21-25,80,139,8080
                          -p fast       -> -F FastMode
                          -p top        -> --top-ports 1000
                          -p default    -> default-scan, turns of -p

    
    -w minutes         -> time in minutes after which an unaltered 
                          nmap_asctual.scan file will return warning
                          default: 1440 *** (only with -x)
                          
    -c minutes         -> time in minutes after which an unaltered 
                          nmap_current.scan file will return critical
                          default: 2880 *** (only with -x)
                          
    -v nagios-version  -> might be 2 (limited output)
                          default: 3 (only with -x)
                          
    -n name(s)         -> use given ip/cidr/dns-name instead of a server_list
                          might be a comma-separated list, eg 
                          192.168.0.12,192.168.0.15,192.168.0.17/32
    

INSTALL:

  - edit this script and change values from # config - section
  - create data_dir, give your nagios-user read and the nmap-user
    rw - access to that directory; you should execute your nmap-scans
    as an unprivileged user via crontab, NOT via nagios/nrpe, due to timeouts
  - define your networks/hostlist to scan
  - create a check (see below)


Create a check
  
  interactively:
    - run check_nmap -i [profile-name]; data-directories and server.lst
      will be created within data_dir
    
  manually:

    - create [data_dir]/profile-name (see value for data_dir below)
      in section DATA
    - create a file called servers.lst in [data_dir]/profile-name
      with a list of servers to scan (might be omitted using switch -n )
    - (not needed at the moment):
      edit value profiles => add new profile-name/description to dictionary
    - run check_nmap -i [profile-name]

  always:
    - add cronjob for check_nmap -x [profile-name]
    - add service-check for check_nmap -x [profile-name]
    - run forest, run
    

DATA_DIR:
  default -> %s
  
  you might change the value for [data_dir] within the header 
  of this script for your own needs
  
  data is stored below [data_dir] as follows:
  
    [data_dir]/[profile-name]/
                server.lst        => list with servers to scan
                                     might be omitted using switch -n 
                nmap_initial.scan => scan-result created during profile-init
                                     (using -i switch)
                nmap_current.scan => actual scan_result, created from cronjob
                scan.log          => action-log
                ndiff.log         => ndiff-log (***)


        
    """ % (version, data_dir)

def return_nagios():
    nagios_status = "NMAP %s - %s" % (return_status, return_output)    
    print nagios_status
    sys.exit(return_code)


def print_debug(in_put):
    
    if debug == "yes":
        print "d: %s" % in_put


def scan_log(out_text, scan_log_file):
    actual_time=time.strftime("%F %H:%M", time.localtime(time.time()))
    
    try:
        f = open(scan_log_file, "a")
        f.write("%s  :: %s \n" % (actual_time, out_text))
        f.close()
    except:
        pass
    return()



def nmap_scan(profile):
    global profile_name
    profile_name = profile
    
    if not os.path.isdir(scan_data_dir):
        print "ERROR!! no scan_data_dir found -> %s \n > does it exists???\n > ... exiting ..." % scan_data_dir
        sys.exit(2)
    if os.access("%s" % nmap_exec, os.X_OK) == False:
        print """
        
ERROR ... nmap_executable not found / not executable 
          -> %s
 
 > ... exiting        
        """ % nmap_exec
        sys.exit(2)
    if list == "yes":
        if not os.path.isfile(server_file):
            print "ERROR!! no server_file found -> %s \n > does it exists???\n > ... exiting ..." % server_file
            sys.exit()

    nmap_command = "%s %s %s -oX %s %s %s " % (nmap_exec, nmap_switches, nmap_ports, scan_current_file, nmap_list_switch, server_file)
    try:
        os.system(nmap_command)
        #os.popen(nmap_command).readlines() 
    except:
        print """
        
ERROR while trying to execute scan  
          -> %s
 
 > ... exiting        
        """ % nmap_command
        sys.exit(2)
    try:
        os.system("sudo chgrp %s %s " % (nagios_group, scan_current_file))
        os.system("sudo chmod 640 %s " % scan_current_file)
    except:
        print "cannot chgroup/chmod %s for nagios-access" % scan_current_file

    scan_log("[%s] :: SCAN  nmap run -> %s " % (profile, nmap_command), scan_log_file)


def nmap_init(profile):
    global profile_name
    profile_name = profile
    
    
    run_time = time.strftime("%Y-%m-%d_%H:%M", time.localtime(time.time()))
    
    if not os.path.isdir(scan_data_dir):
        try:
            os.makedirs(scan_data_dir)
        except:
            print "ERROR!! cannot create scan_data_dir  -> %s \n > do you have rw_rights to %s ???\n > ... exiting ..." % data_dir
            sys.exit(2)
    
    if os.access("%s" % nmap_exec, os.X_OK) == False:
        print """
        
ERROR ... nmap_executable not found / not executable 
          -> %s
 
 > ... exiting        
        """ % nmap_exec
        sys.exit(2)


    if not os.path.isfile(server_file):
        print "[i] no server_file found -> %s \n > ... creating ..." % server_file

        servers = []
        s_in = ""
        print "> [q] to quit and write file %s " % server_file
        while s_in != "q":
            s_in = raw_input("> add server/net to server.lst: ")
            if s_in == "q":
                break
            if len(s_in) < 5:
                print "> [q] to quit and write file %s " % server_file
                continue
            else:
                servers.append(s_in.strip())
        
        print "\n\n------------------------------\n> going to add now: \n"
        for s in servers:
            print "   - %s" % s
        
        write_file = raw_input("> write server.lst [Y|n] ")
        if write_file != "n":
            scan_log("creating server.lst -> %s" % server_file) 
            f = open(server_file, "w")
            for s in servers:
                scan_log("  - added %s" % s) 
                f.write("%-s \n" % s)
            
            f.write("\n\n# end \n")
            f.close()
            print "> file written ->  %s " % server_file
            
            
        
            
        
    if os.path.isfile(scan_init_file):
        print "deleting old init-file"
        try:
            os.system("chmod 600 %s " % scan_init_file)
            os.system("rm -f %s " % scan_init_file)
        except:
            os.system("chmod 600 %s " % scan_init_file)
            os.system("rm -f %s " % scan_init_file)
    

    nmap_command = "%s %s %s -oX %s %s %s " % (nmap_exec, nmap_switches, nmap_ports, scan_init_file, nmap_list_switch, server_file)
    print_debug(nmap_command)
    
    try:
        os.system(nmap_command)
        #os.popen(nmap_command).readlines() 
    except:
        print """
        
ERROR while trying to execute scan  
          -> %s
 
 > ... exiting        
        """ % nmap_command
        sys.exit(2)
    
    scan_log("[%s] :: INIT nmap run -> %s " % (profile, nmap_command), scan_log_file)
    os.system("sudo chgrp %s %s " % (nagios_group, scan_init_file))
    os.system("sudo chmod 440 %s " % scan_init_file)
    os.system("sudo chgrp %s %s " % (nagios_group, scan_data_dir))
    os.system("sudo chmod 750 %s " % scan_data_dir)
    
    sys.exit()

def nmap_check(profile):
    global return_status, return_output, return_code, return_perfdata

    return_status = "UNKNOWN"
    return_output = "unknow status for nmap-scan"
    return_code = 3
    return_perfdata = 0

    
    if not os.path.isdir(scan_data_dir):
        return_status = "UNKNOWN"
        return_output = "SCAN_DATA_DIR[%s] does not exist for nmap-check -> %s " % (scan_data_dir, profile)
        return_code = 3
        return_nagios()
    if os.access("%s" % ndiff_exec, os.X_OK) == False:
        return_status = "UNKNOWN"
        return_output = "nmap_exectuable not found -> %s for nmap-check -> %s " % (ndiff_exec, profile)
        return_code = 3
        return_nagios()
    if not os.path.isfile(scan_init_file):
        return_status = "UNKNOWN"
        return_output = "SCAN_INIT_FILE[%s] not found -> %s for nmap-check -> %s " % (scan_init_file, profile)
        return_code = 3
        return_nagios()

    if not os.path.isfile(scan_current_file):
        return_status = "UNKNOWN"
        return_output = "SCAN_CURRENT_FILE[%s] not found -> %s for nmap-check -> %s " % (scan_current_file, profile)
        return_code = 3
        return_nagios()

    
    # puft in check for current_timestamp
    
    ndiff_command = "%s %s %s " % (ndiff_exec, scan_init_file, scan_current_file)
    try:
        ndiff_out = os.popen(ndiff_command).readlines()
        #os.popen(nmap_command).readlines() 
    except:
        return_status = "UNKNOWN"
        return_output = "ERRO while executing -> %s @ nmap-check -> %s " % (ndiff_command, profile)
        return_code = 3
        return_nagios()
    
    ndc = 0
    for line in ndiff_out:
        if line.find("Nmap") > -1:
            continue
        elif line.find("Not shown") > -1:
            continue
        elif line.find("open") > -1:
            ndc += 1
            return_output = "%s -> %s" % (return_output, line.strip())
            continue
        elif line.find("closed") > -1:
            ndc += 1
            return_output = "%s -> %s" % (return_output, line.strip())
            continue
        elif line.find("filtered") > -1:
            ndc += 1
            return_output = "%s -> %s" % (return_output, line.strip())
            continue
                    
    
    if ndc < 1:
        return_status = "OK"
        return_output = "nmap-check passed -> profile: %s " % (profile)
        return_code = 0
        return_nagios()
    else:
        return_output = "DIFF found: %s" % return_output
        return_status = "CRITICAL"
        return_code = 2
        out_len = len(ndiff_out)
        #print out_len
            
        if nagios_version == "3":
            return_output = "%s \n%s" % (return_output, string.join(ndiff_out, ""))         
        return_nagios()

    
# Argument parsing
if len(sys.argv) < 2:
    check_nmap_help()
    sys.exit(2) 

try:
    opts, args = getopt.getopt(sys.argv[1:], "i:x:n:s:c:w:v:p:dhP" )
except getopt.GetoptError, err:
    # print help information and exit:
    print str(err) # will print something like "option -a not recognized"
    sys.exit(2)


do = "buttin"
list = "yes"
ping_scan = "no"

for o, a in opts:
    #print "o :: " + o + "   <-->  a: " + a
    if o == "-v":
        nagios_version = a

    elif o == "-d":
        debug = "yes"    
        nmap_switches = nmap_switches + " --version-trace"

    
    elif o == "-h":
        check_nmap_help()
        exit(0)

    elif o == "-n":
        list = "no"
        names = string.join(string.split(a, ","), " ")

    elif o == "-s":
        profile = a
        do = "scan"

    elif o == "-P":
        ping_scan = "no"
        nmap_switches = nmap_switches + " -PN "
        
    elif o == "-p":
        if a == "fast":
            nmap_ports = " -F "
        elif a == "top":
            nmap_ports = " --top-ports 1000 "
        elif a == "default":
            nmap_ports = " "
        else:
            nmap_ports = " -p %s " % a


    elif o == "-x":
        profile = a
        do = "check"

    elif o == "-i":
        profile = a
        do = "init"

    elif o == "-w":
        try:
            scan_fresh_warning = int(a)
            scan_fresh_warning = "%s" % a
        except:
            pass

    elif o == "-c":
        try:
            scan_fresh_critical = int(a)
            scan_fresh_critical = "%s" % a
        except:
            pass


nmap_list_switch = "-iL"
scan_data_dir = "%s/%s" % (data_dir, profile)
server_file = "%s/server.lst" % scan_data_dir
scan_init_file = "%s/nmap_initial.scan" % scan_data_dir
scan_current_file = "%s/nmap_current.scan" % scan_data_dir
scan_log_file = "%s/scan.log" % scan_data_dir

if list == "no":
    nmap_list_switch = ""
    server_file = names    

if do == "buttin":
    pass

elif do == "scan":
    nmap_scan(profile)
    sys.exit()

elif do == "init":
    nmap_init(profile)
    sys.exit()

elif do == "check":
    nmap_check(profile)
    

return_status = "UNKNOWN"
return_output = "unknown status in nmap-scan"
return_code = 3
return_nagios()
