#!/usr/bin/python
#
# check_selenium.py / executes from selenium-ide exported
#                     checks and parses output
# part of nagdog
#
# (c) copyright 2009,2010,2011,2012,2013 dogtown@mare-system.de
#
#
# v 0.4.12 - AALPHAA - 2013-01-10
# 
# 

import os, posix, string, sys, time, getopt

# where the testcases are stored, must be python_exports from selenium ide 
test_dir="/srv/data/selenium_tests"

# check for running browser-procs, set to no to disable
#-> check for max_procs (firefox)
check_for_procs = "yes"
max_procs_allowed = 15
browser_cmd = "firefox-bin"

# defaults
warning_t="15"
critical_t="30"
test_count="none"
debug = "no"

return_status="UNKNOWN"
return_exit=3
return_text="no return (default)"
return_perfdata="none"

def check_selenium_help():
    print """

check_selenium 
    nagios_plugin to check selenium_tests and display results / perfdata
    
    USAGE
     check_selenium [options]
     
    OPTIONS
      -s [scriptname] 
            test_script to execute
            must be located in $test_dir 

      -t [count] 
            number of test that must be executed; if number
            differs, status==WARNING
            default: off 

      -w [seconds]
            threshold in seconds for the test to pass
            to change status to WARNING
            default: 15 sek

      -c [seconds] 
            threshold in seconds for the test to pass
            to change status to CRITICAL
            default: 30sek
            
      -d    turn debug on
      
      -p [procs] 
            checks for running (*browser*) processes; 
            exits if too many running procs found
            default: 15
            
      
    
    """

    

def return_result():
    
    rp = return_perfdata.strip()
    if rp[-1] != ";":
        rp = "%s;" % rp
    print "SELENIUM %s %s | %s " % (return_status, return_text, rp)
    sys.exit(return_exit)

def print_debug(debug_output):
    if debug == "yes":
        print "d:: %s " % debug_output
    return()
        

try:
    opts, args = getopt.getopt(sys.argv[1:], "s:c:w:t:p:hdz", 
        ["help", "script", "debug" ])
except getopt.GetoptError, err:
    # print help information and exit:
    print str(err) # will print something like "option -a not recognized"
    check_selenium_help()
    sys.exit(2)


for o, a in opts:
    #print "o :: " + o + "   <-->  a: " + a
    if o in ("-s", "--script"):
        test_script = a
        test_script_path = "%s/%s" % (test_dir, test_script)
    elif o in ("-h", "--help"):
        check_selenium_help()
        sys.exit()
        

    elif o in ("-w", "--warning"):
        warning_t = a
    elif o in ("-c", "--critical"):
        critical_t = a
        
    elif o == "-t":
        test_count = a
    
    elif o == "-d":
        debug = "yes"

    elif o == "-p":
        
        try:
            max_procs_allowed = int(a)
        except:
            pass
    
    else:
        check_selenium_help()
        sys.exit(2)        

if len(sys.argv) == 1:
    check_selenium_help()
    sys.exit(0)

if not test_script:
    return_text = "no testscript given"
    return_status="CRITICAL"
    return_exit = 2
    return_result()

if not os.path.exists(test_script_path):
    return_text = "no testscript found in %s " % test_script_path
    return_status="CRITICAL"
    return_exit = 2
    return_result()


if check_for_procs != "no":
    running = os.popen("ps -ef | grep %s" % browser_cmd).readlines()
    if len(running) > max_procs_allowed:
        return_exit = 1
        return_status == "WARNING"
        return_text = "Proc.FAIL: to much running processes found; running: %s :: allowd: %s  (checking: %s )" % (len(running), max_procs_allowed, test_script) 
        return_perfdata = test_out_compiled
        return_result()
        sys.exit(2)


print_debug("excuting %s in %s " % (test_script, test_dir))

test_output = os.popen("cd %s && python %s 2>&1 " % (test_dir, test_script)).readlines()

print_debug(test_output)

test_out_compiled = string.join(test_output, "")


# return if test failed 
if test_out_compiled.find("FAIL") > -1:
    return_exit = 2
    return_status == "CRITICAL"
    return_text = "FAIL: not all tests passed -> %s " % (test_script) 
    return_perfdata = test_out_compiled
    return_result()
    sys.exit(2)

out_string = string.strip(test_output[2])
out_status = string.strip(test_output[4])

out_time = float((string.split(out_string, "test in")[1]).replace("s", ""))

print_debug(out_time)
return_perfdata = "checktime=%ss;" % int(out_time)

if out_status == "OK":
    try:
        wt = float(warning_t)
    except:
        return_text = "Warning-Time (-w) must be a number"
        return_result()

    try:
        ct = float(critical_t)
    except:
        return_text = "Critical-Time (-c) must be a number"
        return_result()

    if out_time > ct:
        return_status = "CRTITICAL"
        return_exit = 2
        return_text = "all tests passed, but time exceeds > %s s (%s)" % (ct,return_perfdata)
        return_result()
    elif out_time > wt:
        return_status = "WARNING"
        return_exit = 1
        return_text = "all tests passed, but time exceeds > %s s (%s)" % (wt,return_perfdata)
        return_result()

         
    return_exit = 0
    return_status = "OK"
    return_text = "all tests passed from %s  ( %s )" % (test_script, int(out_time))
else:
    return_exit = 2
    return_status == "CRITICAL"
    return_text = "not all tests passed :: %s -> %s " % (out_status, test_script) 

return_result()

    

